name: SSWG-MVM Auto Changelog

on:
  push:
    tags: ["v*"]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0   # needed for full commit history

      - name: Install git-cliff
        run: |
          curl -sSL https://github.com/orhun/git-cliff/releases/download/v2.2.0/git-cliff-2.2.0-x86_64-unknown-linux-musl.tar.gz -o cliff.tar.gz
          tar -xvf cliff.tar.gz
          sudo mv git-cliff /usr/local/bin/

      - name: Generate Changelog
        run: |
          git cliff --tag $GITHUB_REF_NAME --output CHANGELOG.md

      - name: Commit & Push Changelog
        run: |
          git config --global user.name "SSWG-MVM Auto-Changelog"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "Auto-generate changelog for $GITHUB_REF_NAME" || echo "No changes"
          git push
